# Generated by Django 4.2.3 on 2023-08-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_alter_fotografia_publicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('BAIXA IMPORTÂNCIA', 'Baixa importância'), ('MODERAMENTE IMPORTANTE', 'Moderamente importânte'), ('IMPORTANTE', 'Importante'), ('MUITO IMPORTANTE', 'Muito importante')], default='', max_length=100),
        ),
    ]
