# Generated by Django 4.2.3 on 2023-08-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_alter_fotografia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='estado',
            field=models.CharField(choices=[('Em andamento', 'Em andamento'), ('Concluído', 'Concluído')], default='Em andamento', max_length=20),
        ),
    ]
