# Generated by Django 4.2.3 on 2023-08-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_alter_fotografia_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Em andamento', 'Em andamento'), ('Concluida', 'Concluida')], default='Em andamento', max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('quantidade_passos', models.PositiveIntegerField()),
                ('data_conclusao', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fotografia',
            name='estado',
        ),
    ]
