# Generated by Django 4.2.3 on 2023-08-04 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0012_meta_remove_fotografia_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meta',
        ),
    ]
