# Generated by Django 4.2.3 on 2023-08-05 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0014_meta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meta',
        ),
    ]
