# Generated by Django 4.2.3 on 2023-08-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0015_delete_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='estado',
            field=models.CharField(choices=[('Em andamento', 'Em andamento'), ('Concluido', 'Concluido')], default='Concluido', max_length=20),
        ),
    ]
