# Generated by Django 4.2.3 on 2023-08-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0016_fotografia_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='FazerMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeMeta', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('quantidade_passos', models.IntegerField()),
            ],
        ),
    ]
