# Generated by Django 4.2.3 on 2023-08-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0017_fazermeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='estado',
            field=models.CharField(choices=[('Em andamento', 'Em andamento'), ('Concluido', 'Concluido')], default='Em andamento', max_length=20),
        ),
    ]
