# Generated by Django 4.2.3 on 2023-08-06 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0019_fazermeta_modo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_passo', models.PositiveIntegerField()),
                ('descricao', models.TextField()),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.fazermeta')),
            ],
        ),
    ]
