# Generated by Django 4.2.3 on 2023-08-06 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0020_passo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passo',
        ),
    ]
