# Generated by Django 4.2.3 on 2023-08-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0021_delete_passo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FazerAnotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo1', models.CharField(max_length=100)),
            ],
        ),
    ]
