# Generated by Django 4.2.3 on 2023-08-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0022_fazeranotacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fazeranotacao',
            name='campo1',
        ),
        migrations.AddField(
            model_name='fazeranotacao',
            name='anotacao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fazeranotacao',
            name='nomeAnotacao',
            field=models.CharField(blank=True, default='', max_length=4000),
        ),
    ]
