# Generated by Django 4.2.3 on 2023-08-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0024_rename_anotacao_fazeranotacao_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fazeranotacao',
            name='nomeAnotacao',
            field=models.CharField(max_length=1000),
        ),
    ]
