# Generated by Django 4.2.3 on 2023-08-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0025_alter_fazeranotacao_nomeanotacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='FazerTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeTarefa', models.CharField(max_length=100)),
                ('data_entrega', models.DateField()),
                ('modo', models.CharField(choices=[('Tarefa em andamento', 'Tarefa em andamento'), ('Tarefa Concluida', 'Tarefa Concluida')], default='Tarefa em andamento', max_length=20)),
            ],
        ),
    ]
